version: 1.0.{build}
#environment:
#  sitePath: c:\websites\fromYamlTop
install:
- appveyor-retry nuget restore
#nuget issue workaround
hosts:
  api.nuget.org: 93.184.221.200
  
build_script:
- msbuild "WebApplication3\WebApplication3.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Package /p:PackageLocation=%APPVEYOR_BUILD_FOLDER%\myapp.zip
- appveyor PushArtifact myapp.zip -Type WebDeployPackage -DeploymentName AppDeploymentName
deploy:
- provider: Environment
  name: IIS2
  sitePath: C:\websites\foo bar\website
- provider: WebDeploy
  server: https://ilyaf3.scm.azurewebsites.net/msdeploy.axd?site=ilyaf3
  website: ilyaf3
  #website: ilyaf3/vApp1
  username: $ilyaf3
  password:
    secure: wo3gqImLjckquy1VnmwSL/S6H1Q1m7t6iKUGcvhKrzDDTIsBB2Qd2rz6Nmz6d9i9nTT5B1ci017GElrkKdf0ow==
  artifact: AppDeploymentName

- provider: Local
  AppDeploymentName.deploy_website: true
