version: 1.0.{build}
install:
- nuget restore
build_script:
- msbuild "WebApplication3\WebApplication3.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Package /p:PackageLocation=%APPVEYOR_BUILD_FOLDER%\myapp.zip
- appveyor PushArtifact myapp.zip -Type WebDeployPackage -DeploymentName AppDeploymentName
deploy:
- provider: Environment
  name: IIS2
- provider: WebDeploy
  server: https://ilyaf3.scm.azurewebsites.net/msdeploy.axd?site=ilyaf3
  website: ilyaf3
  username: $ilyaf3
  password:
    secure: wo3gqImLjckquy1VnmwSL/S6H1Q1m7t6iKUGcvhKrzDDTIsBB2Qd2rz6Nmz6d9i9nTT5B1ci017GElrkKdf0ow==
  artifact: AppDeploymentName
